# Generated by Django 3.2.9 on 2021-11-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='hashtag',
            field=models.CharField(max_length=100, null=True, verbose_name='해시태그'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='메뉴명'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='pat',
            field=models.CharField(max_length=100, null=True, verbose_name='조리종류'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='way',
            field=models.CharField(max_length=100, null=True, verbose_name='조리방법'),
        ),
    ]
