# Generated by Django 3.2.9 on 2021-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='메뉴 수'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredients_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='재료 수'),
        ),
    ]
