# Generated by Django 3.2.9 on 2021-11-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211110_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredients_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='메뉴 카운트'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=200, verbose_name='메뉴명'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Ingredients ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='재료명')),
                ('count', models.PositiveIntegerField(default=0, editable=False, verbose_name='메뉴 카운트')),
                ('menus', models.ManyToManyField(related_name='ingredients_set', to='app.Menu')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
