# Generated by Django 3.2.9 on 2021-11-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_menu_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='carb',
            field=models.FloatField(verbose_name='탄수화물'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='energy',
            field=models.FloatField(verbose_name='열량'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fat',
            field=models.FloatField(verbose_name='지방'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='na',
            field=models.FloatField(verbose_name='나트륨'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='protein',
            field=models.FloatField(verbose_name='단백질'),
        ),
    ]
