# Generated by Django 3.2.9 on 2021-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211117_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredients_parsed',
            field=models.TextField(blank=True, default='', verbose_name='파싱된 재료정보'),
        ),
    ]
