# Generated by Django 3.2.9 on 2021-11-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211112_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='count',
            field=models.PositiveIntegerField(default=None, editable=False, verbose_name='메뉴 카운트'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredients_count',
            field=models.PositiveIntegerField(default=None, editable=False, verbose_name='메뉴 카운트'),
        ),
    ]
