# Generated by Django 3.2.9 on 2021-11-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211105_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Menu ID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Recipe ID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menu',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='app.menu', verbose_name='조리메뉴'),
        ),
    ]
