# Generated by Django 3.2.9 on 2021-11-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211105_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='menu',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='app.menu', verbose_name='조리메뉴'),
        ),
    ]
